'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const p=require('../services/resolutionProviders'),old=require('../services/marketResolutionRule'),schema=require('../database/settlement-schema');
const r=require('../services/officialResolutionRules');
const upbit={version:1,provider:'upbit',market:'KRW-BTC',metric:'minute_close',operator:'gt',threshold:100,observation_at:'2026-10-06T09:00:00.000Z',missing_data_policy:'cancel_after_24h'};
const weather={version:2,provider:'awc_metar',station:'RKSI',metric:'temperature_c',operator:'gt',threshold:17,observation_at:'2099-10-06T09:00:00.000Z',missing_data_policy:'cancel_after_24h'};
const issue={title:r.officialTitle(weather),category:'날씨',end_date:weather.observation_at,betting_end_date:'2099-10-06T03:00:00.000Z'};issue.description=p.officialDescription(weather,issue);
test('Upbit validator key and reason remain identical',()=>{assert.deepEqual(p.validateRule(upbit),old.validateResolutionRule(upbit));assert.equal(p.ruleKey(upbit),schema.resolutionKey(upbit));assert.equal(p.resolutionReason(upbit,{status:'Yes',evidence:{candle_open_at:'2026-10-06T08:59:00.000Z',close:101}}),'업비트 KRW-BTC 2026-10-06T08:59:00.000Z 1분봉 종가 101원, 기준 100원 초과 여부: Yes.');});
test('unknown provider/version never dispatches or reaches fetch',async()=>{for(const rule of[{...weather,provider:'arbitrary'}, {...weather,version:1},{...upbit,version:2}]){assert.throws(()=>p.validateRule(rule),/Unsupported/);await assert.rejects(async()=>p.resolveRule(rule,{fetchImpl:async()=>assert.fail('No fetch')}));}});
test('new flag never silently enables when only old flag true',()=>{assert.equal(p.providerEnabled(weather,{upbit:true,official:false}),false);assert.equal(p.providerEnabled(upbit,{upbit:true,official:false}),true);assert.equal(p.providerEnabled(weather,{upbit:false,official:true}),true);assert.equal(p.providerEnabled(upbit,{upbit:false,official:true}),false);});
test('provider status advertises only verified categories',()=>{const s=p.providerStatus({upbit:true,official:false});assert.deepEqual(s.map(x=>x.category),['코인','날씨','경제']);assert.deepEqual(s.map(x=>x.enabled),[true,false,false]);});
test('new public criteria must match exact source category and title',()=>{assert.deepEqual(p.publicCriteria(weather,issue),weather);for(const change of[{title:'Wrong threshold'},{category:'스포츠'},{description:'Missing criteria'},{description:issue.description+'\n'+issue.description},{description:issue.description+'\nYEGAM-FORGED'}])assert.throws(()=>p.publicCriteria(weather,{...issue,...change}));});
test('publication checks feature flag and actual future betting window',()=>{const previous=process.env.AUTO_RESOLVE_OFFICIAL;try{delete process.env.AUTO_RESOLVE_OFFICIAL;assert.throws(()=>p.assertPublishable(weather,issue,{now:0}),/not enabled/);process.env.AUTO_RESOLVE_OFFICIAL='true';assert.deepEqual(p.assertPublishable(weather,issue,{now:Date.parse('2099-10-05T00:00:00Z')}),weather);assert.throws(()=>p.assertPublishable(weather,issue,{now:Date.parse(issue.betting_end_date)}),/future/);}finally{if(previous===undefined)delete process.env.AUTO_RESOLVE_OFFICIAL;else process.env.AUTO_RESOLVE_OFFICIAL=previous;}});

test('contradictory leading or trailing prose is never part of v2 issue criteria',()=>{for(const description of['17°C 미만이면 Yes\n'+issue.description,issue.description+'\n내일이 아닌 지금 값으로 판정',issue.description+'\n기준 단위는 화씨'])assert.throws(()=>p.publicCriteria(weather,{...issue,description}),/Exact canonical/);});

test('weather activation never enables unverified Treasury provider',()=>{const treasury={provider:'us_treasury',version:2};assert.equal(p.providerEnabled(treasury,{official:true,treasury:false}),false);assert.equal(p.providerEnabled(treasury,{official:false,treasury:true}),false);assert.equal(p.providerEnabled(treasury,{official:true,treasury:true}),true);assert.equal(p.providerEnabled(weather,{official:true,treasury:false}),true);});
